### ISSUE TITLE
mkvirtualenv fail python3 

### ISSUE THREAD

**Issue by MichaelMartinez** [brainsik/virtualenv-burrito#24]
### got this error:

``` bash
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.3.0/Frameworks/Python.framework/Versions/3.3'
New python executable in testpy3/bin/python3
Also creating executable in testpy3/bin/python
Installing distribute......................................................................................................................................................................................................................................................................................................................................................................................................done.
Installing pip..........
  Complete output from command /Users/mam/.virtualenvs/testpy3/bin/python3 -x /Users/mam/.virtuale...py3/bin/easy_install /Users/mam/.venvburr...ort/pip-1.2.1.tar.gz:
  Traceback (most recent call last):
  File "/Users/mam/.virtualenvs/testpy3/bin/easy_install", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/mam/.venvburrito/lib/python/distribute-0.6.32-py2.7.egg/pkg_resources.py", line 45
    def _bypass_ensure_directory(name, mode=0777):
                                               ^
SyntaxError: invalid token
----------------------------------------
...Installing pip...done.
Traceback (most recent call last):
  File "/Users/mam/.venvburrito/lib/python/virtualenv-1.8.4-py2.7.egg/virtualenv.py", line 2560, in <module>
    main()
  File "/Users/mam/.venvburrito/lib/python/virtualenv-1.8.4-py2.7.egg/virtualenv.py", line 964, in main
    never_download=options.never_download)
  File "/Users/mam/.venvburrito/lib/python/virtualenv-1.8.4-py2.7.egg/virtualenv.py", line 1076, in create_environment
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download)
  File "/Users/mam/.venvburrito/lib/python/virtualenv-1.8.4-py2.7.egg/virtualenv.py", line 667, in install_pip
    filter_stdout=_filter_setup)
  File "/Users/mam/.venvburrito/lib/python/virtualenv-1.8.4-py2.7.egg/virtualenv.py", line 1042, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/mam/.virtualenvs/testpy3/bin/python3 -x /Users/mam/.virtuale...py3/bin/easy_install /Users/mam/.venvburr...ort/pip-1.2.1.tar.gz failed with error code 1
```

let me know if I can be of further assistance

**Comment by brainsik** [comment]
@switham Regarding setting PYTHONPATH, I'm tracking that in #55.

**Comment by RustyRaptor** [comment]
So has this been fixed?
