### ISSUE TITLE
No such file or directory: '/tmp/venvburrito.kQS7i1/setuptools-39.0.1'

### ISSUE THREAD

**Issue by Quiescitus** [brainsik/virtualenv-burrito#75]
This is what I get when I run
`curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL`

```
Running: virtualenv-burrito upgrade firstrun
+ setuptools will upgrade (None -> 39.0.1)
+ pip will upgrade (None -> 9.0.3)
+ virtualenv will upgrade (None -> 15.2.0)
+ virtualenvwrapper will upgrade (None -> 4.8.2)
  Downloading setuptools-39.0.1.zip …
* Upgrading setuptools …
  Installing setuptools-39.0.1
tar: This does not look like a tar archive
tar: Skipping to next header
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/quiescitus/.venvburrito/bin/virtualenv-burrito", line 293, in <module>
    main(sys.argv)
  File "/home/quiescitus/.venvburrito/bin/virtualenv-burrito", line 283, in main
    handle_upgrade(firstrun=True)
  File "/home/quiescitus/.venvburrito/bin/virtualenv-burrito", line 241, in handle_upgrade
    upgrade_package(filename, name, version)
  File "/home/quiescitus/.venvburrito/bin/virtualenv-burrito", line 160, in upgrade_package
    os.chdir(os.path.join(tmp, realname))
OSError: [Errno 2] No such file or directory: '/tmp/venvburrito.kQS7i1/setuptools-39.0.1'
```
It feels like something is very wrong with my $PYTHONPATH, but I'm not sure. Any pointers?

**Comment by antonywu** [comment]
I got similar issue. The OS complains about the missing directory, but I think the real issue is that setuptools-39.0.1 wasn't downloaded successfully. Hence "not look like a tar archive" And since, there is nothing to untar, the directory is not created. Would need to dig into the code to see where it downloads setuptools from

> antony@linux:~$ virtualenv-burrito upgrade
> + setuptools will upgrade (28.8.0 -> 39.0.1)
> + pip will upgrade (9.0.1 -> 9.0.3)
> + virtualenv will upgrade (15.1.0 -> 15.2.0)
> + virtualenvwrapper will upgrade (4.7.2 -> 4.8.2)
>   Downloading setuptools-39.0.1.zip …
> * Upgrading setuptools …
>   Installing setuptools-39.0.1
> tar: This does not look like a tar archive
> tar: Skipping to next header
> gzip: stdin has more than one entry--rest ignored
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> Traceback (most recent call last):
>   File "/home/antony/.venvburrito/bin/virtualenv-burrito", line 293, in <module>
>     main(sys.argv)
>   File "/home/antony/.venvburrito/bin/virtualenv-burrito", line 287, in main
>     handle_upgrade()
>   File "/home/antony/.venvburrito/bin/virtualenv-burrito", line 241, in handle_upgrade
>     upgrade_package(filename, name, version)
>   File "/home/antony/.venvburrito/bin/virtualenv-burrito", line 160, in upgrade_package
>     os.chdir(os.path.join(tmp, realname))
> OSError: [Errno 2] No such file or directory: '/tmp/venvburrito.fIbgR2/setuptools-39.0.1'
>

**Comment by antonywu** [comment]
I did a code trace.

For upgrade or installation, it is based off this [file](https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/versions.csv). setuptools points to https://pypi.python.org/packages/72/c2/c09362ab29338413ab687b47dab03bab4a792e2bbb727a1eb5e0a88e3b86/setuptools-39.0.1.zip

It is not a tarball. It is a zip file. The function `upgrade_package` currently is clueless about how to handle zip file

**Comment by mattrobenolt** [comment]
Hmm, I tested this myself when I pushed this change and it worked fine. Lemme see what I can do here.

**Comment by antonywu** [comment]
Well, inside `upgrade_package` it treats every file as tarball. Even the comment section said so. 

```
# unpack the tarball
sh("tar xfz %s -C %s" % (filename, tmp))
```

**Comment by mattrobenolt** [comment]
Yup. :) Just unclear why this worked for me when I ran it. I'll try and get this fixed up today, or revert. Sorry about that.
